In [1]:
from sklearn import metrics

C:\Users\Lenovo\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Lenovo\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
c='cat'
d='dog'
f='fox'

### the precision for the cat class is the number of correctly predicated cat out of all predicted cat


### the recall for cat number of correctly predicted cat photos out of the number of actual cat

In [3]:
#TRUE VALUES
y_true=[c,c,c,c,c,c, f,f,f,f,f,f,f,f,f,f, d,d,d,d,d,d,d,d,d,d,]

#PREDICATED VALUES
y_pred=[c,c,c,c,d,f, c,c,c,c,c,c,d,d,f,f, c,c,c,d,d,d,d,d,d,d]

In [4]:
#PRINT THE CONFUSION METRICS
print(metrics.confusion_matrix(y_true,y_pred))

[[4 1 1]
 [3 7 0]
 [6 2 2]]


In [5]:
#PRINT PRECISION AND RECALL
print(metrics.classification_report(y_true,y_pred))

              precision    recall  f1-score   support

         cat       0.31      0.67      0.42         6
         dog       0.70      0.70      0.70        10
         fox       0.67      0.20      0.31        10

    accuracy                           0.50        26
   macro avg       0.56      0.52      0.48        26
weighted avg       0.60      0.50      0.48        26

